version: '3'
services:
  prism:
    image: stoplight/prism:4
    command: mock -d -h 0.0.0.0 /spec/openapi.yaml
    volumes:
      - ./src/api/open_api/openapi.yaml:/spec/openapi.yaml
    ports:
      - 4010:4010

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/spec/openapi.yaml
    volumes:
      - ./src/api/open_api/openapi.yaml:/spec/openapi.yaml
    ports:
      - 8080:8080
