name: GKE Deploy

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 2: Authenticate Docker to GCR
      - name: Authenticate Docker to Google Container Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # - name: Auth Docker GCP
      # run: gcloud auth login.

      # Step 3: Build Docker image
      - name: Build Docker image
        #  run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/guess-the-number:$GITHUB_SHA .
        run: docker build -t guess-the-number .

      - name: Tag Docker image
        run: docker tag guess-the-number us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/guess-the-number:$GITHUB_SHA

      - name: Auth Docker to GCR
        run: gcloud auth configure-docker us-docker.pkg.dev

      # Step 4: Push Docker image to GCR
      - name: Push Docker image to GCR
        # run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/guess-the-number:$GITHUB_SHA
        run: docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/guess-the-number:$GITHUB_SHA

      # Step 5: Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      # Step 6: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/guess-the-number-deployment guess-the-number=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/guess-the-number:$GITHUB_SHA
