openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
servers:
  - url: '{baseUrl}'
    description: 'Dynamic base URL'
    variables:
      baseUrl:
        default: 'http://localhost:4010/'
        description: 'Base URL of the API'
paths:
  /api/v1/users:
    get:
      summary: Get a list of users
      parameters:
        - name: limit
          required: false
          in: query
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                minItems: 10
                maxItems: 10
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  first_name: John
                  last_name: Lennon
                - id: 2
                  first_name: Paul
                  last_name: McCartney
    post:
      summary: Create a new user
      requestBody:
        description: User to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Lennon
        email:
          type: string
          format: email
          example: john.doe@example.com

    NewUser:
      type: object
      properties:
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Lennon
        email:
          type: string
          format: email
          example: john.doe@example.com
